### ISSUE TITLE
Config settings class does not exist

### ISSUE THREAD

**Issue by firewaller** [jienckebd/feeds_crawler#2]
When navigating to /admin/config/system/feeds-crawler, I get the following error:

`Uncaught PHP Exception InvalidArgumentException: "Class "Drupal\feeds_crawler\Form\FeedsCrawlerSettings" does not exist." at /web/core/lib/Drupal/Core/DependencyInjection/ClassResolver.php line 24`

Changing the following in feeds_crawler.info.yml from:
```
feeds_crawler.settings:
  path: '/admin/config/system/feeds-crawler'
  defaults:
    _form: 'Drupal\feeds_crawler\Form\FeedsCrawlerSettings'
```
to:
```
feeds_crawler.settings:
  path: '/admin/config/system/feeds-crawler'
  defaults:
    _form: 'Drupal\feeds_crawler\Form\FeedsCrawlerSettingsForm'
```
fixes the issue.
